"""uppo

Revision ID: 116df760c448
Revises: 4d21b31d4201
Create Date: 2013-05-13 09:29:14.171000

"""

# revision identifiers, used by Alembic.
revision = '116df760c448'
down_revision = '4d21b31d4201'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uppo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('name_p', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uppo')
    ### end Alembic commands ###
