"""pw_hash

Revision ID: 4d21b31d4201
Revises: cecc65111d6
Create Date: 2013-05-06 10:45:21.031000

"""

# revision identifiers, used by Alembic.
revision = '4d21b31d4201'
down_revision = 'cecc65111d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pw_hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pw_hash')
    ### end Alembic commands ###
