"""add url

Revision ID: 5a7198fd5381
Revises: c7f5353cf72
Create Date: 2013-05-05 11:57:09.799000

"""

# revision identifiers, used by Alembic.
revision = '5a7198fd5381'
down_revision = 'c7f5353cf72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kn_post', sa.Column('cover_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kn_post', 'cover_url')
    ### end Alembic commands ###
