"""init

Revision ID: c7f5353cf72
Revises: None
Create Date: 2013-05-05 11:35:34.265000

"""

# revision identifiers, used by Alembic.
revision = 'c7f5353cf72'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
