"""last_login_date

Revision ID: cecc65111d6
Revises: 5a7198fd5381
Create Date: 2013-05-05 16:22:44.999000

"""

# revision identifiers, used by Alembic.
revision = 'cecc65111d6'
down_revision = '5a7198fd5381'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_date')
    ### end Alembic commands ###
